=== HudsonLiang/JavaScratchBook/non-drive/build/resources/main/roadrotation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://github.com/HudsonLiang/roadrotation" elementFormDefault="unqualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://github.com/HudsonLiang/roadrotation">



    <element name="Rules">
    	<complexType>
    		<sequence>
    			<element name="WeekDayRule" type="tns:WeekDayRuleType" maxOccurs="unbounded" minOccurs="1"></element>
    		</sequence>
    	</complexType></element>

    <complexType name="WeekDayRuleType">
    	<sequence>
    		<element name="WeekDaySequence" minOccurs="1" maxOccurs="5">
    			<simpleType>
    				<restriction base="string"></restriction>
    			</simpleType>
    		</element>
    	</sequence>
    	<attribute name="onDate" type="date" use="required"></attribute>
    	<attribute name="offDate" type="date" use="required"></attribute>
    </complexType>

    <complexType name="BaseRuleType"></complexType>
</schema>

=== HudsonLiang/JavaScratchBook/non-drive/build/resources/main/rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Rules xmlns:tns="http://github.com/HudsonLiang/roadrotation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://github.com/HudsonLiang/roadrotation roadrotation.xsd ">
	<WeekDayRule onDate="2017-10-09" offDate="2018-01-07">
		<WeekDaySequence>1,6</WeekDaySequence>
		<WeekDaySequence>2,7</WeekDaySequence>
		<WeekDaySequence>3,8</WeekDaySequence>
		<WeekDaySequence>4,9</WeekDaySequence>
		<WeekDaySequence>0,5</WeekDaySequence>
	</WeekDayRule>
	<WeekDayRule onDate="2018-01-08" offDate="2018-04-08">
		<WeekDaySequence>0,5</WeekDaySequence>
		<WeekDaySequence>1,6</WeekDaySequence>
		<WeekDaySequence>2,7</WeekDaySequence>
		<WeekDaySequence>3,8</WeekDaySequence>
		<WeekDaySequence>4,9</WeekDaySequence>
	</WeekDayRule>
	<WeekDayRule onDate="2017-04-10" offDate="2017-07-09">
		<WeekDaySequence>3,8</WeekDaySequence>
		<WeekDaySequence>4,9</WeekDaySequence>
		<WeekDaySequence>5,0</WeekDaySequence>
		<WeekDaySequence>6,1</WeekDaySequence>
		<WeekDaySequence>7,2</WeekDaySequence>
	</WeekDayRule>
	<WeekDayRule onDate="2017-07-09" offDate="2017-10-08">
		<WeekDaySequence>2,7</WeekDaySequence>
		<WeekDaySequence>3,8</WeekDaySequence>
		<WeekDaySequence>4,9</WeekDaySequence>
		<WeekDaySequence>5,0</WeekDaySequence>
		<WeekDaySequence>1,6</WeekDaySequence>
	</WeekDayRule>

</tns:Rules>

=== HudsonLiang/JavaScratchBook/java8newfeatures/src/test/resources/roadrotation.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Rules xmlns:tns="http://github.com/HudsonLiang/roadrotation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://github.com/HudsonLiang/roadrotation roadrotation.xsd ">
	<WeekDayRule offDate="2015-07-11" onDate="2015-04-03">
		<WeekDaySequence>1,6</WeekDaySequence>
		<WeekDaySequence>2,7</WeekDaySequence>
		<WeekDaySequence>3,8</WeekDaySequence>
		<WeekDaySequence>4,9</WeekDaySequence>
		<WeekDaySequence>0,5</WeekDaySequence>
	</WeekDayRule>
	<WeekDayRule offDate="2015-10-10" onDate="2015-07-12">
		<WeekDaySequence>0,5</WeekDaySequence>
		<WeekDaySequence>1,6</WeekDaySequence>
		<WeekDaySequence>2,7</WeekDaySequence>
		<WeekDaySequence>3,8</WeekDaySequence>
		<WeekDaySequence>4,9</WeekDaySequence>
	</WeekDayRule>
	<WeekDayRule offDate="2016-04-10" onDate="2016-01-10">
		<WeekDaySequence>3,8</WeekDaySequence>
		<WeekDaySequence>4,9</WeekDaySequence>
		<WeekDaySequence>5,0</WeekDaySequence>
		<WeekDaySequence>6,1</WeekDaySequence>
		<WeekDaySequence>7,2</WeekDaySequence>
	</WeekDayRule>
</tns:Rules>
